# VERSION 1 CONFIG VARIABLES
[v1]

NODE_ENV= "development"

# NODE VERSION BASE PATH
APP_SRC_PATH= "/api/v1"

# VARIABLE FOR SETTING SECRET KEY OF ENCRYPTION/DECRYPTION
ENC_KEY="ab9b7df503dfa524510573fb0fca6cf04732d9b891ced8fee514181ce93aa7c2"

# JWT SECRET VARIABLE FOR CUSTOMER
JWT_SECRET="7d9bc963c315f1ca46c00531d3753209648b43beda2552de3bea0b897a2ffc1e"

# VARIABLE FOR JWT EXPIRY DAYS
JWT_EXPIRY = "30d"

#SALT
SALT = 12

# RESET URL
RESET_URL = "http://localhost:8000"

EMAIL_HOST_SERVER="smtpout.secureserver.net"
EMAIL_PORT=465
EMAIL_USERNAME="info@designprintnyc.com"
EMAIL_PASSWORD="design_PRINT2024"